# Generated by Django 5.1.2 on 2024-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories_clients_reservations_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
